version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
  mongo:
    image: mongo
    ports:
      - "27017:27017"